global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: mysql-exporter
    static_configs:
      - targets: ['mysqld-exporter:9104']

  - job_name: redis-exporter
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: kafka-exporter
    static_configs:
      - targets: ['kafka-exporter:9308']

  - job_name: command-service
    static_configs:
      - targets: ['host.docker.internal:28081']

  - job_name: outbox-relay
    static_configs:
      - targets: ['host.docker.internal:28082']

  - job_name: consumer-service
    static_configs:
      - targets: ['host.docker.internal:28083']

  - job_name: query-service
    static_configs:
      - targets: ['host.docker.internal:28084']
